/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pack;

public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b83726048a7d90d45a2d125ae3566d7 (do not edit this line) */
