/* Generated By:JJTree: Do not edit this line. ASTRhs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pack;

public
class ASTRhs extends SimpleNode {
  public ASTRhs(int id) {
    super(id);
  }

  public ASTRhs(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68109ac5fab2ac8d4e2c212411ee1245 (do not edit this line) */
