/* Generated By:JJTree: Do not edit this line. ASTString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pack;

public
class ASTString extends SimpleNode {
  public ASTString(int id) {
    super(id);
    type = "String";
  }

  public ASTString(MyNewGrammar p, int id) {
    super(p, id);
    type = "String";

  }

}
/* JavaCC - OriginalChecksum=fc1a7a1c6b48cb60beb9184886bd0247 (do not edit this line) */
